### ISSUE TITLE
Broken with Craft 2.6?

### ISSUE THREAD

**Issue by shealan** [nfourtythree/craft-entriessubset#1]
/home/vagrant/website/craft/plugins/entriessubset/fieldtypes/EntriesSubsetFieldType.php(73)

```
61             $entryTypeOptions[] = array('label' => $type->name, 'value' => $type->id);
62         }
63 
64         return $entryTypeOptions;
65     }
66 
67     public function getInputTemplateVariables($name, $criteria)
68     {
69         $variables = parent::getInputTemplateVariables($name, $criteria);
70 
71         $entryTypes = $this->getSettings()->entryTypes;
72 
73         foreach($this->getSettings()->entryTypes as $typeId) {
74             if ($typeId != "*") {
75                 $entryType = craft()->sections->getEntryTypeById($typeId);
76                 $variables['criteria']['type'][] = $entryType->handle;
77             }
78         }
79 
80         return $variables;
81     }
82 }
```

Just tried to use this excellent plugin on a 2.6 install and I am getting this? Any ideas? Hate to build a website without this plugin :(

**Comment by nfourtythree** [comment]
@shealan I haven't had a chance to look into compatibility with 2.6 as of yet, I know there was a number of changes in relation to the Element Criteria Model due to the new Eager Loading functionality.

I should be able to take a look at this later and get a fix up and running. Especially as I am about to set this up on a new 2.6 site myself!

**Comment by shealan** [comment]
I've just created the field again from scratch using a different name and it's no longer throwing an error. It's possible it was trying to parse some data from the fieldtype I was using before. If so false alarm! See how you get on. Thanks for a great plugin :)

**Comment by nfourtythree** [comment]
Just tested this on 2.6.2774 and everything seems to be working as expected

**Comment by shealan** [comment]
This has happened a few more times when I have tried to use this plugin for a few more fields. Very weird. Have you not seen any errors at all?

**Comment by nfourtythree** [comment]
That is odd, any chance you can drop me the whole error either from the page or the logs? Is it on the Front-end or the CP

**Comment by shealan** [comment]
It's always when used within a Matrix if that helps?

It's on the frontend, when I try and open the page the field is used on via the control panel. Same error about "Invalid argument supplied for foreach()".

**Comment by nfourtythree** [comment]
@shealan Just pushed a release that should hopefully fix this. If you are still getting an issue I will look further into it later 

https://github.com/nfourtythree/craft-entriessubset/releases/tag/0.5.1

**Comment by shealan** [comment]
@nfourtythree Seems to work now. Will keep a close eye on it and report back if I find anything. Thanks!
